### ISSUE TITLE
 Window-AC-Web-API main file

### ISSUE THREAD

**Issue by cab113** [dippnerd/Window-AC-Web-API#1]
Hi, im trying to build this project, i couldnt locate your source file so i got it from a forked linked in your repo. im having errors at two places in the code my error file is attached.

[new error log.txt](https://github.com/dippnerd/Window-AC-Web-API/files/4413100/new.error.log.txt)

error at Webapp:app

any help will be appreciated.
Thanks 
Ronald

**Comment by dippnerd** [comment]
hey Ronald, so sorry about that! the code should be up now. i'd give this one a shot, i wouldn't be surprised if the other stuff is outdated but this source is running on one of my ACs 2 years strong now.

**Comment by cab113** [comment]
Hi, i thank you for getting back to my question. I have tried the latest file but it wont compile.
Error at Webapp app does not name a type.

Is there a local file you used together to compile these project. Im using Arduino 1.8.12

**Comment by dippnerd** [comment]
sorry, I haven't touched this stuff in a while, but the #include stuff at the top points to the libraries you'll need, i think most of it should be in the Arduino library manager (Tools>Manage Libraries on mine), but i'll dig around my notes to see if i can find everything
